### ISSUE TITLE
Битая ссылка

### ISSUE THREAD

**Issue by leshchenko1979** [Zzoomrus/Zapret-AmneziaVPN#1]
Упомянута ссылка на https://github.com/nikrays/Zapret-on-Keenetic/blob/master/readme.md, но она не рабочая.

**Comment by Zzoomrus** [comment]
Да, действительно, репозиторий удален. Можно воспользоваться статьей на Хабре, [вот тут](https://habr.com/ru/articles/834826/). Поправлю инструкцию когда освобожусь обязательно, спасибо за указание проблемы!

**Comment by Zzoomrus** [comment]
Исправлено

**Comment by Zzoomrus** [comment]
Исравлено
